from pycastle.config import Config
from pycastle.iteration.planning_issue_intake import (
    BlockerSummaryInputs,
    LabelSyncAction,
    evaluate_planning_readiness,
    planning_blocker_summary,
)


def test_evaluate_planning_readiness_reports_malformed_bodies_and_excludes_them():
    cfg = Config()
    ready = {
        "number": 1,
        "title": "Ready",
        "body": "x" * 100,
        "comments": [],
        "labels": ["behavior-slice"],
    }
    none_body = {
        "number": 2,
        "title": "None body",
        "body": None,
        "comments": [],
        "labels": ["behavior-slice"],
    }
    whitespace_body = {
        "number": 3,
        "title": "Whitespace",
        "body": " \n\t ",
        "comments": [],
        "labels": ["docs-slice"],
    }
    at_marker_body = {
        "number": 4,
        "title": "@- marker",
        "body": "@-",
        "comments": [],
        "labels": ["refactor-slice"],
    }

    result = evaluate_planning_readiness(
        [ready, none_body, whitespace_body, at_marker_body],
        cfg,
    )

    assert result.ready_candidates == (ready,)
    assert result.malformed_body_issues == (
        none_body,
        whitespace_body,
        at_marker_body,
    )


def test_evaluate_planning_readiness_reports_needs_info_label_actions():
    cfg = Config(needs_info_label="awaiting-details")
    malformed_unflagged = {
        "number": 2,
        "title": "Too short",
        "body": "short",
        "comments": [],
        "labels": ["behavior-slice"],
    }
    well_formed_flagged = {
        "number": 3,
        "title": "Recovered",
        "body": "x" * 100,
        "comments": [],
        "labels": ["docs-slice", "awaiting-details"],
    }
    malformed_flagged = {
        "number": 4,
        "title": "Already synced",
        "body": " \n\t ",
        "comments": [],
        "labels": ["refactor-slice", "awaiting-details"],
    }

    result = evaluate_planning_readiness(
        [malformed_unflagged, well_formed_flagged, malformed_flagged],
        cfg,
    )

    assert result.label_sync_actions == (
        LabelSyncAction(
            issue_number=2,
            label_name="awaiting-details",
            intent="add",
            comment_body=(
                "> *This was generated by AI during triage.*\n\n"
                "This issue is labeled `ready-for-agent` but its body is too short "
                "(must be at least 100 characters after stripping whitespace).\n\n"
                "The implement phase skips this issue until content is added.\n"
                "`needs-info` will be removed automatically once the body meets "
                "the minimum length."
            ),
        ),
        LabelSyncAction(
            issue_number=3,
            label_name="awaiting-details",
            intent="remove",
        ),
    )


def test_evaluate_planning_readiness_keeps_needs_info_adds_before_removes():
    cfg = Config(needs_info_label="awaiting-details")
    well_formed_flagged = {
        "number": 3,
        "title": "Recovered",
        "body": "x" * 100,
        "comments": [],
        "labels": ["docs-slice", "awaiting-details"],
    }
    malformed_unflagged = {
        "number": 2,
        "title": "Too short",
        "body": "short",
        "comments": [],
        "labels": ["behavior-slice"],
    }

    result = evaluate_planning_readiness(
        [well_formed_flagged, malformed_unflagged],
        cfg,
    )

    assert result.label_sync_actions[:2] == (
        LabelSyncAction(
            issue_number=2,
            label_name="awaiting-details",
            intent="add",
            comment_body=(
                "> *This was generated by AI during triage.*\n\n"
                "This issue is labeled `ready-for-agent` but its body is too short "
                "(must be at least 100 characters after stripping whitespace).\n\n"
                "The implement phase skips this issue until content is added.\n"
                "`needs-info` will be removed automatically once the body meets "
                "the minimum length."
            ),
        ),
        LabelSyncAction(
            issue_number=3,
            label_name="awaiting-details",
            intent="remove",
        ),
    )


def test_evaluate_planning_readiness_both_malformed_body_and_missing_slice_produces_both_actions():
    cfg = Config()
    issue = {
        "number": 1,
        "title": "Doubly malformed",
        "body": "short",
        "comments": [],
        "labels": [],
    }

    result = evaluate_planning_readiness([issue], cfg)

    assert result.ready_candidates == ()
    assert result.malformed_body_issues == (issue,)
    assert result.malformed_slice_mode_issues == (issue,)
    action_intents = [(a.label_name, a.intent) for a in result.label_sync_actions]
    assert (cfg.needs_info_label, "add") in action_intents
    assert (cfg.needs_slice_type_label, "add") in action_intents


def test_evaluate_planning_readiness_syncs_needs_slice_type_for_missing_and_multiple_modes():
    cfg = Config(needs_slice_type_label="needs-mode")
    ready_flagged = {
        "number": 1,
        "title": "Recovered",
        "body": "x" * 100,
        "comments": [],
        "labels": ["behavior-slice", "needs-mode"],
    }
    missing_unflagged = {
        "number": 2,
        "title": "Missing mode",
        "body": "x" * 100,
        "comments": [],
        "labels": [],
    }
    multiple_unflagged = {
        "number": 3,
        "title": "Two modes",
        "body": "x" * 100,
        "comments": [],
        "labels": ["docs-slice", "behavior-slice"],
    }
    multiple_flagged = {
        "number": 4,
        "title": "Already synced",
        "body": "x" * 100,
        "comments": [],
        "labels": ["refactor-slice", "docs-slice", "needs-mode"],
    }

    result = evaluate_planning_readiness(
        [ready_flagged, missing_unflagged, multiple_unflagged, multiple_flagged],
        cfg,
    )

    assert result.ready_candidates == (ready_flagged,)
    assert result.malformed_slice_mode_issues == (
        missing_unflagged,
        multiple_unflagged,
        multiple_flagged,
    )
    assert result.label_sync_actions == (
        LabelSyncAction(
            issue_number=2,
            label_name="needs-mode",
            intent="add",
            comment_body=(
                "> *This was generated by AI during triage.*\n\n"
                "This issue is labeled `ready-for-agent` but is missing exactly "
                "one slice-mode label.\n"
                "Expected one of: `refactor-slice`, `behavior-slice`, "
                "`docs-slice`.\n"
                "Current slice labels: none.\n\n"
                "The implement phase skips this issue until the labeling is fixed.\n"
                "`needs-slice-type` will be removed automatically once a single "
                "slice label is set."
            ),
        ),
        LabelSyncAction(
            issue_number=3,
            label_name="needs-mode",
            intent="add",
            comment_body=(
                "> *This was generated by AI during triage.*\n\n"
                "This issue is labeled `ready-for-agent` but is missing exactly "
                "one slice-mode label.\n"
                "Expected one of: `refactor-slice`, `behavior-slice`, "
                "`docs-slice`.\n"
                "Current slice labels: `docs-slice`, `behavior-slice`.\n\n"
                "The implement phase skips this issue until the labeling is fixed.\n"
                "`needs-slice-type` will be removed automatically once a single "
                "slice label is set."
            ),
        ),
        LabelSyncAction(
            issue_number=1,
            label_name="needs-mode",
            intent="remove",
        ),
    )


def test_evaluate_planning_readiness_exposes_blocker_summary_readiness_groups():
    from pycastle.issue_readiness import IssueReadinessKind

    cfg = Config()
    missing_slice = {
        "number": 1,
        "title": "Missing mode",
        "body": "x" * 100,
        "comments": [],
        "labels": [],
    }
    short_body = {
        "number": 2,
        "title": "Short body",
        "body": "short",
        "comments": [],
        "labels": ["behavior-slice"],
    }
    doubly_malformed = {
        "number": 3,
        "title": "Both",
        "body": "tiny",
        "comments": [],
        "labels": ["docs-slice", "behavior-slice"],
    }

    result = evaluate_planning_readiness(
        [missing_slice, short_body, doubly_malformed],
        cfg,
    )

    assert [
        readiness.kind
        for readiness in result.blocker_summary_inputs.malformed_slice_mode_readiness
    ] == [
        IssueReadinessKind.MISSING_SLICE_MODE,
        IssueReadinessKind.MALFORMED,
    ]
    assert [
        readiness.kind
        for readiness in result.blocker_summary_inputs.malformed_body_readiness
    ] == [
        IssueReadinessKind.SHORT_BODY,
        IssueReadinessKind.MALFORMED,
    ]
    assert result.ready_readiness_by_number == {}


def test_evaluate_planning_readiness_exposes_ready_readiness_by_number():
    from pycastle.issue_readiness import IssueReadinessKind, SliceMode

    cfg = Config()
    ready = {
        "number": 9,
        "title": "Ready",
        "body": "x" * 100,
        "comments": [],
        "labels": ["docs-slice"],
    }

    result = evaluate_planning_readiness([ready], cfg)

    assert result.ready_candidates == (ready,)
    assert result.ready_readiness_by_number[9].kind == IssueReadinessKind.READY_AFK
    assert result.ready_readiness_by_number[9].selected_mode == SliceMode.DOCS


def test_prepare_planning_issue_set_ignores_hitl_exempt_issues_for_label_sync_and_blocker_summary():
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    ready = {
        "number": 1,
        "title": "Ready",
        "body": "x" * 100,
        "comments": [],
        "labels": ["docs-slice"],
    }
    hitl_exempt = {
        "number": 2,
        "title": "Human-owned",
        "body": "short",
        "comments": [],
        "labels": ["ready-for-human"],
    }

    prepared = prepare_planning_issue_set([ready, hitl_exempt], cfg)

    assert prepared.ready_candidates == (ready,)
    assert prepared.label_sync_actions == ()
    assert prepared.malformed_body_issues == ()
    assert prepared.malformed_slice_mode_issues == ()
    assert planning_blocker_summary(prepared.blocker_summary_inputs) is None


def test_planning_blocker_summary_uses_readiness_groups():
    from pycastle.issue_readiness import (
        IssueReadiness,
        IssueReadinessKind,
        Malformed,
        MalformedBody,
        WellFormedBody,
    )

    summary = planning_blocker_summary(
        BlockerSummaryInputs(
            malformed_slice_mode_readiness=(
                IssueReadiness(
                    slice_status=Malformed(found=[]),
                    body_floor_status=WellFormedBody(stripped_length=100),
                    is_ready=False,
                    selected_mode=None,
                    kind=IssueReadinessKind.MISSING_SLICE_MODE,
                ),
            ),
            malformed_body_readiness=(
                IssueReadiness(
                    slice_status=Malformed(found=["behavior-slice", "docs-slice"]),
                    body_floor_status=MalformedBody(stripped_length=4),
                    is_ready=False,
                    selected_mode=None,
                    kind=IssueReadinessKind.MALFORMED,
                ),
            ),
        )
    )

    assert (
        summary == "Planning blockers: 1 missing exactly one slice-mode label; "
        "1 body is below the minimum length floor."
    )


def test_planning_blocker_summary_returns_none_when_no_blockers():
    assert planning_blocker_summary(BlockerSummaryInputs()) is None


def test_planning_blocker_summary_uses_plural_label_noun_for_multiple_slice_issues():
    from pycastle.issue_readiness import (
        IssueReadiness,
        IssueReadinessKind,
        Malformed,
        WellFormedBody,
    )

    two_missing_slice = tuple(
        IssueReadiness(
            slice_status=Malformed(found=[]),
            body_floor_status=WellFormedBody(stripped_length=100),
            is_ready=False,
            selected_mode=None,
            kind=IssueReadinessKind.MISSING_SLICE_MODE,
        )
        for _ in range(2)
    )
    summary = planning_blocker_summary(
        BlockerSummaryInputs(malformed_slice_mode_readiness=two_missing_slice)
    )

    assert summary == "Planning blockers: 2 missing exactly one slice-mode labels."


def test_planning_readiness_compatibility_shim_reexports_issue_intake_interface():
    from pycastle.iteration import planning_issue_intake, planning_readiness

    assert (
        planning_readiness.BlockerSummaryInputs
        is planning_issue_intake.BlockerSummaryInputs
    )
    assert planning_readiness.LabelSyncAction is planning_issue_intake.LabelSyncAction
    assert (
        planning_readiness.PlanningReadinessResult
        is planning_issue_intake.PlanningReadinessResult
    )
    assert (
        planning_readiness.evaluate_planning_readiness
        is planning_issue_intake.evaluate_planning_readiness
    )
    assert (
        planning_readiness.planning_blocker_summary
        is planning_issue_intake.planning_blocker_summary
    )


def test_prepare_planning_issue_set_strips_stale_blocker_lines():
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    raw_issue = {
        "number": 11,
        "title": "Ready once stale blocker is removed",
        "body": "Summary\n\nBlocked by #99\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }

    result = prepare_planning_issue_set([raw_issue], cfg)

    assert result.ready_candidates == (
        {
            "number": 11,
            "title": "Ready once stale blocker is removed",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
        },
    )


def test_prepare_planning_issue_set_preserves_live_blocker_lines():
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    blocked_issue = {
        "number": 12,
        "title": "Still open blocker",
        "body": "x" * 120,
        "comments": [],
        "labels": ["refactor-slice"],
    }
    dependent_issue = {
        "number": 11,
        "title": "Still blocked",
        "body": "Summary\n\nBlocked by #12, #99\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }

    result = prepare_planning_issue_set([dependent_issue, blocked_issue], cfg)

    assert result.ready_candidates[0]["body"] == dependent_issue["body"]


def test_prepare_planning_issue_set_normalizes_missing_fields_and_preserves_blocker_inputs():
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    raw_issue = {
        "number": 21,
        "title": "Malformed",
        "body": None,
        "comments": None,
        "labels": None,
    }

    prepared = prepare_planning_issue_set([raw_issue], cfg)
    legacy = evaluate_planning_readiness([raw_issue], cfg)

    assert prepared.prepared_issues == (
        {
            "number": 21,
            "title": "Malformed",
            "body": "",
            "comments": [],
            "labels": [],
        },
    )
    assert prepared.ready_candidates == ()
    assert prepared.label_sync_actions == legacy.label_sync_actions
    assert planning_blocker_summary(prepared.blocker_summary_inputs) == (
        planning_blocker_summary(legacy.blocker_summary_inputs)
    )


def test_prepare_planning_issue_set_matches_compatibility_readiness_on_normalized_issue_facts():
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    ready_issue = {
        "number": 31,
        "title": "Ready",
        "body": "x" * 100,
        "comments": [],
        "labels": ["docs-slice"],
    }
    malformed_issue = {
        "number": 32,
        "title": "Malformed",
        "body": "short",
        "comments": [],
        "labels": [],
    }

    prepared = prepare_planning_issue_set([ready_issue, malformed_issue], cfg)
    legacy = evaluate_planning_readiness(list(prepared.prepared_issues), cfg)

    assert prepared.ready_candidates == legacy.ready_candidates
    assert prepared.ready_readiness_by_number == legacy.ready_readiness_by_number
    assert prepared.malformed_body_issues == legacy.malformed_body_issues
    assert prepared.malformed_slice_mode_issues == legacy.malformed_slice_mode_issues
    assert prepared.label_sync_actions == legacy.label_sync_actions
    assert prepared.blocker_summary_inputs == legacy.blocker_summary_inputs


def test_prepare_planning_issue_set_reuses_compatibility_readiness_after_stale_blocker_stripping():
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    raw_issue = {
        "number": 33,
        "title": "Ready after stale blocker stripping",
        "body": "Summary\n\nBlocked by #99\n\n" + ("x" * 120),
        "comments": None,
        "labels": ["behavior-slice"],
    }

    prepared = prepare_planning_issue_set([raw_issue], cfg)
    legacy = evaluate_planning_readiness(list(prepared.prepared_issues), cfg)

    assert prepared.prepared_issues == (
        {
            "number": 33,
            "title": "Ready after stale blocker stripping",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
        },
    )
    assert prepared.ready_candidates == legacy.ready_candidates
    assert prepared.ready_readiness_by_number == legacy.ready_readiness_by_number
    assert prepared.malformed_body_issues == legacy.malformed_body_issues
    assert prepared.malformed_slice_mode_issues == legacy.malformed_slice_mode_issues
    assert prepared.label_sync_actions == legacy.label_sync_actions
    assert prepared.blocker_summary_inputs == legacy.blocker_summary_inputs


def test_prepare_planning_issue_set_recomputes_readiness_from_normalized_prepared_issue():
    from pycastle.issue_readiness import classify_issue_readiness
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    raw_issue = {
        "number": 34,
        "title": "Ready after normalization",
        "body": "Summary\n\nBlocked by #99\n\n" + ("x" * 120),
        "comments": None,
        "labels": ["behavior-slice"],
        "readiness": classify_issue_readiness(
            {
                "number": 34,
                "title": "Ready after normalization",
                "body": "short",
                "comments": [],
                "labels": [],
            },
            cfg,
        ),
    }

    prepared = prepare_planning_issue_set([raw_issue], cfg)

    assert prepared.prepared_issues == (
        {
            "number": 34,
            "title": "Ready after normalization",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
        },
    )
    assert prepared.ready_candidates == (
        {
            "number": 34,
            "title": "Ready after normalization",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
        },
    )
    assert 34 in prepared.ready_readiness_by_number
    assert prepared.malformed_body_issues == ()
    assert prepared.malformed_slice_mode_issues == ()


def test_prepare_planning_issue_set_drops_stale_ready_readiness_for_normalized_malformed_issue():
    from pycastle.issue_readiness import classify_issue_readiness
    from pycastle.iteration.planning_issue_intake import prepare_planning_issue_set

    cfg = Config()
    raw_issue = {
        "number": 35,
        "title": "Malformed after normalization",
        "body": "Blocked by #99\n\n" + ("x" * 95),
        "comments": None,
        "labels": None,
        "readiness": classify_issue_readiness(
            {
                "number": 35,
                "title": "Malformed after normalization",
                "body": "x" * 120,
                "comments": [],
                "labels": ["behavior-slice"],
            },
            cfg,
        ),
    }

    prepared = prepare_planning_issue_set([raw_issue], cfg)

    normalized_issue = {
        "number": 35,
        "title": "Malformed after normalization",
        "body": "\n" + ("x" * 95),
        "comments": [],
        "labels": [],
    }
    assert prepared.prepared_issues == (normalized_issue,)
    assert prepared.ready_candidates == ()
    assert prepared.ready_readiness_by_number == {}
    assert prepared.malformed_body_issues == (normalized_issue,)
    assert prepared.malformed_slice_mode_issues == (normalized_issue,)


def test_resolve_planner_issue_intake_drops_non_ready_numbers_and_uses_prepared_issue_shape():
    from pycastle.iteration.planning_issue_intake import (
        PlanReady,
        prepare_planning_issue_set,
        resolve_planner_issue_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\nBlocked by #99\n\n" + ("x" * 120),
        "comments": None,
        "labels": ["behavior-slice"],
    }
    malformed_issue = {
        "number": 12,
        "title": "Malformed",
        "body": "x" * 120,
        "comments": [],
        "labels": [],
    }
    prepared = prepare_planning_issue_set([ready_issue, malformed_issue], cfg)
    planner_output = PlanReady(
        issues=[
            {"number": 11, "title": "Planner title"},
            {"number": 12, "title": "Planner picked malformed"},
            {"number": 99, "title": "Hallucinated"},
        ],
        sha="plan-sha",
    )

    result = resolve_planner_issue_intake(planner_output, prepared)

    assert result.sha == "plan-sha"
    assert result.issues == [
        {
            "number": 11,
            "title": "Canonical ready title",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
            "readiness": result.readiness_by_number[11],
        }
    ]


def test_resolve_planner_issue_intake_preserves_duplicate_planner_selections():
    from pycastle.iteration.planning_issue_intake import (
        PlanReady,
        prepare_planning_issue_set,
        resolve_planner_issue_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)
    planner_output = PlanReady(
        issues=[
            {"number": 11, "title": "First selection"},
            {"number": 11, "title": "Duplicate selection"},
        ],
        sha="plan-sha",
    )

    result = resolve_planner_issue_intake(planner_output, prepared)

    assert [issue["number"] for issue in result.issues] == [11, 11]
    assert result.issues[0] == result.issues[1]


def test_resolve_planner_issue_intake_uses_prepared_issue_shape_over_planner_echo():
    from pycastle.issue_readiness import IssueReadinessKind, SliceMode
    from pycastle.iteration.planning_issue_intake import (
        PlanReady,
        prepare_planning_issue_set,
        resolve_planner_issue_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)
    planner_output = PlanReady(
        issues=[
            {
                "number": 11,
                "title": "Planner title",
                "body": "planner body",
                "comments": ["planner comment"],
                "labels": ["docs-slice"],
                "readiness": "planner readiness",
            }
        ],
        sha="plan-sha",
    )

    result = resolve_planner_issue_intake(planner_output, prepared)

    assert result.issues == [
        {
            "number": 11,
            "title": "Canonical ready title",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
            "readiness": result.readiness_by_number[11],
        }
    ]
    assert result.readiness_by_number[11].kind == IssueReadinessKind.READY_AFK
    assert result.readiness_by_number[11].selected_mode == SliceMode.BEHAVIOR


def test_resolve_planner_issue_intake_drops_malformed_selected_issue_numbers():
    from pycastle.iteration.planning_issue_intake import (
        PlanReady,
        prepare_planning_issue_set,
        resolve_planner_issue_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)
    planner_output = PlanReady(
        issues=[
            {"number": "11", "title": "Malformed string selection"},
            {"number": 11, "title": "Valid selection"},
        ],
        sha="plan-sha",
    )

    result = resolve_planner_issue_intake(planner_output, prepared)

    assert result.sha == "plan-sha"
    assert result.issues == [
        {
            "number": 11,
            "title": "Canonical ready title",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
            "readiness": result.readiness_by_number[11],
        }
    ]
    assert set(result.readiness_by_number) == {11}


def test_resolve_planner_issue_intake_drops_bool_selected_issue_numbers():
    from pycastle.iteration.planning_issue_intake import (
        PlanReady,
        prepare_planning_issue_set,
        resolve_planner_issue_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 1,
        "title": "Canonical ready title",
        "body": "Summary\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)
    planner_output = PlanReady(
        issues=[
            {"number": True, "title": "Malformed bool selection"},
            {"number": 1, "title": "Valid selection"},
        ],
        sha="plan-sha",
    )

    result = resolve_planner_issue_intake(planner_output, prepared)

    assert result.sha == "plan-sha"
    assert result.issues == [
        {
            "number": 1,
            "title": "Canonical ready title",
            "body": "Summary\n\n" + ("x" * 120),
            "comments": [],
            "labels": ["behavior-slice"],
            "readiness": result.readiness_by_number[1],
        }
    ]
    assert set(result.readiness_by_number) == {1}


def test_resolve_planner_blocked_intake_uses_prepared_ready_titles():
    from pycastle.iteration.planning_issue_intake import (
        prepare_planning_issue_set,
        resolve_planner_blocked_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\nBlocked by #99\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)

    result = resolve_planner_blocked_intake(
        [
            {
                "number": 11,
                "title": "Planner supplied stale title",
                "blocked_by": 3,
                "reason": "depends on #3",
            }
        ],
        prepared,
    )

    assert result == [{"number": 11, "title": "Canonical ready title"}]


def test_resolve_planner_blocked_intake_keeps_only_tolerated_fields_for_unknown_numbers():
    from pycastle.iteration.planning_issue_intake import (
        prepare_planning_issue_set,
        resolve_planner_blocked_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)

    result = resolve_planner_blocked_intake(
        [
            {"number": 21, "title": "Planner supplied title", "note": "waiting"},
            {"number": 22, "blocked_by": 3, "reason": "depends on #3"},
        ],
        prepared,
    )

    assert result == [
        {"number": 21, "title": "Planner supplied title"},
        {"number": 22},
    ]


def test_resolve_planner_all_blocked_intake_uses_canonical_ready_titles():
    from pycastle.agents.output_protocol import PlannerOutput
    from pycastle.iteration.planning_issue_intake import (
        prepare_planning_issue_set,
        resolve_planner_all_blocked_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\nBlocked by #99\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)

    result = resolve_planner_all_blocked_intake(
        PlannerOutput(
            issues=[],
            blocked=[
                {
                    "number": 11,
                    "title": "Planner supplied stale title",
                    "blocked_by": 3,
                    "reason": "depends on #3",
                }
            ],
        ),
        prepared,
    )

    assert result == [{"number": 11, "title": "Canonical ready title"}]


def test_resolve_planner_all_blocked_intake_keeps_tolerated_unknown_fields_only():
    from pycastle.agents.output_protocol import PlannerOutput
    from pycastle.iteration.planning_issue_intake import (
        prepare_planning_issue_set,
        resolve_planner_all_blocked_intake,
    )

    cfg = Config()
    ready_issue = {
        "number": 11,
        "title": "Canonical ready title",
        "body": "Summary\n\n" + ("x" * 120),
        "comments": [],
        "labels": ["behavior-slice"],
    }
    prepared = prepare_planning_issue_set([ready_issue], cfg)

    result = resolve_planner_all_blocked_intake(
        PlannerOutput(
            issues=[],
            blocked=[
                {"number": 21, "title": "Planner supplied title", "note": "waiting"},
                {"number": 22, "blocked_by": 3, "reason": "depends on #3"},
            ],
        ),
        prepared,
    )

    assert result == [
        {"number": 21, "title": "Planner supplied title"},
        {"number": 22},
    ]
