import dataclasses
from typing import Literal, TypeAlias

from ..config import Config
from ..issue_readiness import (
    BODY_FLOOR,
    WellFormed,
    WellFormedBody,
    classify_issue_readiness,
)


LabelActionIntent: TypeAlias = Literal["add", "remove"]


@dataclasses.dataclass(frozen=True)
class LabelSyncAction:
    issue_number: int
    label_name: str
    intent: LabelActionIntent
    comment_body: str | None = None


@dataclasses.dataclass(frozen=True)
class BlockerSummaryInputs:
    malformed_slice_mode_issues: tuple[dict, ...] = ()
    malformed_body_issues: tuple[dict, ...] = ()


@dataclasses.dataclass(frozen=True)
class PlanningReadinessResult:
    ready_candidates: tuple[dict, ...] = ()
    malformed_body_issues: tuple[dict, ...] = ()
    malformed_slice_mode_issues: tuple[dict, ...] = ()
    label_sync_actions: tuple[LabelSyncAction, ...] = ()
    blocker_summary_inputs: BlockerSummaryInputs = dataclasses.field(
        default_factory=BlockerSummaryInputs
    )


_NEEDS_INFO_COMMENT = f"""\
> *This was generated by AI during triage.*

This issue is labeled `ready-for-agent` but its body is too short (must be at least \
{BODY_FLOOR} characters after stripping whitespace).

The implement phase skips this issue until content is added.
`needs-info` will be removed automatically once the body meets the minimum length.\
"""


def _needs_info_actions(
    well_formed_body: list[dict],
    malformed_body: list[dict],
    cfg: Config,
) -> tuple[LabelSyncAction, ...]:
    flag = cfg.needs_info_label
    actions: list[LabelSyncAction] = []

    for issue in malformed_body:
        labels: list[str] = issue.get("labels") or []
        if flag in labels:
            continue
        actions.append(
            LabelSyncAction(
                issue_number=issue["number"],
                label_name=flag,
                intent="add",
                comment_body=_NEEDS_INFO_COMMENT,
            )
        )

    for issue in well_formed_body:
        labels = issue.get("labels") or []
        if flag in labels:
            actions.append(
                LabelSyncAction(
                    issue_number=issue["number"],
                    label_name=flag,
                    intent="remove",
                )
            )
    return tuple(actions)


def evaluate_planning_readiness(
    issues: list[dict], cfg: Config
) -> PlanningReadinessResult:
    classified_issues = [
        (issue, classify_issue_readiness(issue, cfg)) for issue in issues
    ]
    slice_malformed = [
        issue
        for issue, readiness in classified_issues
        if not isinstance(readiness.slice_status, WellFormed)
    ]
    body_well_formed = [
        issue
        for issue, readiness in classified_issues
        if isinstance(readiness.body_floor_status, WellFormedBody)
    ]
    body_malformed = [
        issue
        for issue, readiness in classified_issues
        if not isinstance(readiness.body_floor_status, WellFormedBody)
    ]
    ready_candidates = tuple(
        issue for issue, readiness in classified_issues if readiness.is_ready
    )
    return PlanningReadinessResult(
        ready_candidates=ready_candidates,
        malformed_body_issues=tuple(body_malformed),
        malformed_slice_mode_issues=tuple(slice_malformed),
        label_sync_actions=_needs_info_actions(body_well_formed, body_malformed, cfg),
        blocker_summary_inputs=BlockerSummaryInputs(
            malformed_slice_mode_issues=tuple(slice_malformed),
            malformed_body_issues=tuple(body_malformed),
        ),
    )
