import dataclasses
import json
from pathlib import Path
from typing import Protocol

from ..agents.output_protocol import (
    AgentOutputProtocolError,
    AgentRole,
    PlannerOutput,
)
from ..agents.runner import AgentRunnerProtocol, RunRequest
from ..config import Config
from ..prompts.pipeline import PromptTemplate
from ..services import GitService
from ..services.github_service import GithubService
from ..display.status_display import StatusDisplay
from ..agents.classifier import Malformed, WellFormed, classify_slice
from ..infrastructure.worktree import transient_worktree
from ._rows import status_row
from .implement import branch_for
from .preflight import PreflightAFK, PreflightCache, PreflightHITL


BODY_FLOOR = 100

_NEEDS_INFO_COMMENT = f"""\
> *This was generated by AI during triage.*

This issue is labeled `ready-for-agent` but its body is too short (must be at least \
{BODY_FLOOR} characters after stripping whitespace).

The implement phase skips this issue until content is added.
`needs-info` will be removed automatically once the body meets the minimum length.\
"""


def is_well_formed_body(issue: dict) -> bool:
    body = issue.get("body") or ""
    return len(body.strip()) >= BODY_FLOOR


class _PlanningDeps(Protocol):
    cfg: Config
    status_display: StatusDisplay
    agent_runner: AgentRunnerProtocol
    repo_root: Path
    git_svc: GitService
    github_svc: GithubService
    preflight_cache: PreflightCache


@dataclasses.dataclass(frozen=True)
class PlanReady:
    issues: list[dict]
    sha: str


@dataclasses.dataclass(frozen=True)
class AllBlocked:
    blocked: list[dict]


def hydrate_planned_issues(
    plan_result: "PlanReady", open_issues: list[dict]
) -> "PlanReady":
    by_number = {i["number"]: i for i in open_issues}
    hydrated: list[dict] = []
    for issue in plan_result.issues:
        source = by_number.get(issue["number"])
        if source is None:
            raise RuntimeError(
                f"Planner returned issue #{issue['number']} which is not in the "
                f"ready-for-agent open issues list"
            )
        hydrated.append(
            {
                **issue,
                "body": source.get("body") or "",
                "comments": source.get("comments") or [],
                "labels": source.get("labels") or [],
            }
        )
    return PlanReady(issues=hydrated, sha=plan_result.sha)


def partition_by_slice_label(
    issues: list[dict], cfg: "Config"
) -> tuple[list[dict], list[dict]]:
    """Split issues into (well_formed, malformed) by slice-mode label count."""
    well_formed: list[dict] = []
    malformed: list[dict] = []
    for issue in issues:
        if isinstance(classify_slice(issue, cfg), WellFormed):
            well_formed.append(issue)
        else:
            malformed.append(issue)
    return well_formed, malformed


_MALFORMED_COMMENT = """\
> *This was generated by AI during triage.*

This issue is labeled `ready-for-agent` but is missing exactly one slice-mode label.
Expected one of: `refactor-slice`, `behavior-slice`, `docs-slice`.
Current slice labels: {current_slice}.

The implement phase skips this issue until the labeling is fixed.
`needs-slice-type` will be removed automatically once a single slice label is set.\
"""


def _sync_needs_slice_type(
    well_formed: list[dict],
    malformed: list[dict],
    cfg: "Config",
    github_svc: "GithubService",
) -> None:
    flag = cfg.needs_slice_type_label

    for issue in malformed:
        labels: list[str] = issue.get("labels") or []
        if flag in labels:
            continue
        github_svc.add_label_to_issue(issue["number"], flag)
        result = classify_slice(issue, cfg)
        current = result.found if isinstance(result, Malformed) else []
        current_slice = ", ".join(f"`{lbl}`" for lbl in current) or "none"
        github_svc.post_comment(
            issue["number"], _MALFORMED_COMMENT.format(current_slice=current_slice)
        )

    for issue in well_formed:
        labels = issue.get("labels") or []
        if flag in labels:
            github_svc.remove_label_from_issue(issue["number"], flag)


def _sync_needs_info(
    well_formed_body: list[dict],
    malformed_body: list[dict],
    github_svc: "GithubService",
) -> None:
    flag = "needs-info"

    for issue in malformed_body:
        labels: list[str] = issue.get("labels") or []
        if flag in labels:
            continue
        github_svc.add_label_to_issue(issue["number"], flag)
        github_svc.post_comment(issue["number"], _NEEDS_INFO_COMMENT)

    for issue in well_formed_body:
        labels = issue.get("labels") or []
        if flag in labels:
            github_svc.remove_label_from_issue(issue["number"], flag)


def _fill_fields(issues: list[dict]) -> list[dict]:
    return [
        {**i, "body": i.get("body") or "", "comments": i.get("comments") or []}
        for i in issues
    ]


async def planning_phase(
    deps: _PlanningDeps,
    open_issues: list[dict],
    all_open_issues: list[dict],
    in_flight: list[dict] | None = None,
) -> PlanReady | AllBlocked | PreflightHITL | PreflightAFK:
    _in_flight = in_flight or []

    if _in_flight:
        startup_msg = f"checking {len(_in_flight)} in-flight branch(es) labeled {deps.cfg.issue_label}"
    else:
        startup_msg = f"started planning for {len(open_issues)} issue(s) labeled {deps.cfg.issue_label}"

    async with status_row(
        deps.status_display,
        "Plan",
        kind="phase",
        must_close=True,
        initial_phase="Planning",
        startup_message=startup_msg,
    ) as row:
        if _in_flight:
            verdict = await deps.preflight_cache.get_safe_sha(deps)
            if isinstance(verdict, (PreflightHITL, PreflightAFK)):
                row.close(f"preflight gate blocked (issue #{verdict.issue_number})")
                return verdict
            sha = verdict.sha
            nums = ", ".join(f"#{i['number']}" for i in _in_flight)
            row.close(
                f"resuming {len(_in_flight)} in-flight branch(es) ({nums}) labeled"
                f" {deps.cfg.issue_label}, skipping plan agent"
            )
            return PlanReady(issues=_fill_fields(_in_flight), sha=sha)

        verdict = await deps.preflight_cache.get_safe_sha(deps)
        if isinstance(verdict, (PreflightHITL, PreflightAFK)):
            row.close(f"preflight gate blocked (issue #{verdict.issue_number})")
            return verdict
        sha = verdict.sha

        good_body: list[dict] = []
        bad_body: list[dict] = []
        for issue in open_issues:
            (good_body if is_well_formed_body(issue) else bad_body).append(issue)
        _sync_needs_info(good_body, bad_body, deps.github_svc)

        slice_well_formed, slice_malformed = partition_by_slice_label(
            open_issues, deps.cfg
        )
        _sync_needs_slice_type(
            slice_well_formed, slice_malformed, deps.cfg, deps.github_svc
        )

        good_body_numbers = {i["number"] for i in good_body}
        well_formed = [i for i in slice_well_formed if i["number"] in good_body_numbers]

        if len(well_formed) == 1:
            row.close(
                f"only one open issue (#{well_formed[0]['number']}) labeled"
                f" {deps.cfg.issue_label}, skipping plan agent"
            )
            return PlanReady(issues=_fill_fields(well_formed), sha=sha)

        async with transient_worktree("plan-sandbox", sha=sha, deps=deps) as wt:
            try:
                output = await deps.agent_runner.run(
                    RunRequest(
                        name="Plan Agent",
                        template=PromptTemplate.PLAN,
                        mount_path=wt,
                        role=AgentRole.PLANNER,
                        scope_args={
                            "ALL_OPEN_ISSUES_JSON": json.dumps(all_open_issues),
                            "READY_FOR_AGENT_ISSUES_JSON": json.dumps(well_formed),
                        },
                        model=deps.cfg.plan_override.model,
                        effort=deps.cfg.plan_override.effort,
                        stage="plan-sandbox",
                        status_display=deps.status_display,
                        work_body=f"Creating Plan from {len(well_formed)} issues",
                    )
                )
            except AgentOutputProtocolError as exc:
                raise RuntimeError(str(exc)) from exc

            if not isinstance(output, PlannerOutput):
                raise RuntimeError(
                    f"Planner returned unexpected output type: {type(output).__name__}"
                )
            if not output.issues:
                blocked_lines = [
                    f"  #{b['number']} blocked by #{b['blocked_by']}: {b['reason']}"
                    for b in output.blocked
                ]
                if blocked_lines:
                    row.close(
                        "\n".join(
                            ["All ready-for-agent issues are blocked:"] + blocked_lines
                        )
                    )
                else:
                    row.close("All ready-for-agent issues are blocked.")
                return AllBlocked(blocked=output.blocked)

            plan = PlanReady(
                issues=sorted(output.issues, key=lambda i: i["number"]),
                sha=sha,
            )
            hydrated = hydrate_planned_issues(plan, well_formed)
            issue_lines = [
                f"  #{i['number']}: {i['title']} → {branch_for(i['number'])}"
                for i in hydrated.issues
            ]
            row.close(
                "\n".join(
                    [
                        f"Planning complete, implementing {len(hydrated.issues)} issue(s):"
                    ]
                    + issue_lines
                )
            )
            return hydrated
