import dataclasses
from typing import Literal, TypeAlias

from ..config import Config
from ..issue_readiness import (
    AFKBlockedOutcome,
    AFKReadyOutcome,
    BODY_FLOOR,
    IssueReadiness,
    evaluate_issue_afk_readiness,
    resolve_issue_readiness,
)


@dataclasses.dataclass(frozen=True)
class PlanReady:
    issues: list[dict]
    sha: str | None
    readiness_by_number: dict[int, IssueReadiness] = dataclasses.field(
        default_factory=dict
    )


def hydrate_planned_issues(
    plan_result: PlanReady, open_issues: list[dict]
) -> PlanReady:
    by_number = {i["number"]: i for i in open_issues}
    hydrated: list[dict] = []
    readiness_by_number = dict(plan_result.readiness_by_number)
    for issue in plan_result.issues:
        source = by_number.get(issue["number"])
        if source is None:
            continue
        hydrated.append(
            {
                **issue,
                "body": source.get("body") or "",
                "comments": source.get("comments") or [],
                "labels": source.get("labels") or [],
            }
        )
        readiness = source.get("readiness")
        if isinstance(readiness, IssueReadiness):
            readiness_by_number[issue["number"]] = readiness
    return PlanReady(
        issues=hydrated,
        sha=plan_result.sha,
        readiness_by_number=readiness_by_number,
    )


LabelActionIntent: TypeAlias = Literal["add", "remove"]


@dataclasses.dataclass(frozen=True)
class LabelSyncAction:
    issue_number: int
    label_name: str
    intent: LabelActionIntent
    comment_body: str | None = None


@dataclasses.dataclass(frozen=True)
class BlockerSummaryInputs:
    malformed_slice_mode_issues: tuple[dict, ...] = ()
    malformed_body_issues: tuple[dict, ...] = ()
    malformed_slice_mode_readiness: tuple[IssueReadiness, ...] = ()
    malformed_body_readiness: tuple[IssueReadiness, ...] = ()


@dataclasses.dataclass(frozen=True)
class PlanningReadinessResult:
    ready_candidates: tuple[dict, ...] = ()
    ready_readiness_by_number: dict[int, IssueReadiness] = dataclasses.field(
        default_factory=dict
    )
    malformed_body_issues: tuple[dict, ...] = ()
    malformed_slice_mode_issues: tuple[dict, ...] = ()
    label_sync_actions: tuple[LabelSyncAction, ...] = ()
    blocker_summary_inputs: BlockerSummaryInputs = dataclasses.field(
        default_factory=BlockerSummaryInputs
    )


def planning_blocker_summary(blocker_inputs: BlockerSummaryInputs) -> str | None:
    slice_malformed = blocker_inputs.malformed_slice_mode_readiness
    bad_body = blocker_inputs.malformed_body_readiness
    blocker_parts: list[str] = []
    if slice_malformed:
        noun = "label" if len(slice_malformed) == 1 else "labels"
        blocker_parts.append(
            f"{len(slice_malformed)} missing exactly one slice-mode {noun}"
        )
    if bad_body:
        noun = "body is" if len(bad_body) == 1 else "bodies are"
        blocker_parts.append(f"{len(bad_body)} {noun} below the minimum length floor")
    if not blocker_parts:
        return None
    return "Planning blockers: " + "; ".join(blocker_parts) + "."


_NEEDS_INFO_COMMENT = f"""\
> *This was generated by AI during triage.*

This issue is labeled `ready-for-agent` but its body is too short (must be at least \
{BODY_FLOOR} characters after stripping whitespace).

The implement phase skips this issue until content is added.
`needs-info` will be removed automatically once the body meets the minimum length.\
"""

_MALFORMED_SLICE_COMMENT = """\
> *This was generated by AI during triage.*

This issue is labeled `ready-for-agent` but is missing exactly one slice-mode label.
Expected one of: `refactor-slice`, `behavior-slice`, `docs-slice`.
Current slice labels: {current_slice}.

The implement phase skips this issue until the labeling is fixed.
`needs-slice-type` will be removed automatically once a single slice label is set.\
"""


def _needs_info_actions(
    issues_with_outcomes: list[tuple[dict, AFKReadyOutcome | AFKBlockedOutcome]],
    cfg: Config,
) -> tuple[LabelSyncAction, ...]:
    flag = cfg.needs_info_label
    blocked_actions: list[LabelSyncAction] = []
    well_formed_actions: list[LabelSyncAction] = []

    for issue, outcome in issues_with_outcomes:
        labels: list[str] = issue.get("labels") or []
        if isinstance(outcome, AFKBlockedOutcome) and outcome.has_short_body:
            if flag in labels:
                continue
            blocked_actions.append(
                LabelSyncAction(
                    issue_number=issue["number"],
                    label_name=flag,
                    intent="add",
                    comment_body=_NEEDS_INFO_COMMENT,
                )
            )
            continue
        if flag in labels:
            well_formed_actions.append(
                LabelSyncAction(
                    issue_number=issue["number"],
                    label_name=flag,
                    intent="remove",
                )
            )
    return tuple(blocked_actions + well_formed_actions)


def _needs_slice_type_actions(
    issues_with_outcomes: list[tuple[dict, AFKReadyOutcome | AFKBlockedOutcome]],
    cfg: Config,
) -> tuple[LabelSyncAction, ...]:
    flag = cfg.needs_slice_type_label
    malformed_actions: list[LabelSyncAction] = []
    well_formed_actions: list[LabelSyncAction] = []

    for issue, outcome in issues_with_outcomes:
        labels: list[str] = issue.get("labels") or []
        if not (
            isinstance(outcome, AFKBlockedOutcome) and outcome.has_invalid_slice_mode
        ):
            if flag in labels:
                well_formed_actions.append(
                    LabelSyncAction(
                        issue_number=issue["number"],
                        label_name=flag,
                        intent="remove",
                    )
                )
            continue

        if flag in labels:
            continue

        current_slice = (
            ", ".join(f"`{label}`" for label in outcome.current_slice_labels) or "none"
        )
        malformed_actions.append(
            LabelSyncAction(
                issue_number=issue["number"],
                label_name=flag,
                intent="add",
                comment_body=_MALFORMED_SLICE_COMMENT.format(
                    current_slice=current_slice
                ),
            )
        )

    return tuple(malformed_actions + well_formed_actions)


def evaluate_planning_readiness(
    issues: list[dict], cfg: Config
) -> PlanningReadinessResult:
    classified_issues = [
        (issue, resolve_issue_readiness(issue, cfg)) for issue in issues
    ]
    issues_with_outcomes = [
        (
            issue,
            readiness,
            evaluate_issue_afk_readiness({**issue, "readiness": readiness}, cfg),
        )
        for issue, readiness in classified_issues
    ]
    slice_malformed = [
        issue
        for issue, _, outcome in issues_with_outcomes
        if isinstance(outcome, AFKBlockedOutcome) and outcome.has_invalid_slice_mode
    ]
    slice_malformed_readiness = [
        readiness
        for _, readiness, outcome in issues_with_outcomes
        if isinstance(outcome, AFKBlockedOutcome) and outcome.has_invalid_slice_mode
    ]
    body_malformed = [
        issue
        for issue, _, outcome in issues_with_outcomes
        if isinstance(outcome, AFKBlockedOutcome) and outcome.has_short_body
    ]
    body_malformed_readiness = [
        readiness
        for _, readiness, outcome in issues_with_outcomes
        if isinstance(outcome, AFKBlockedOutcome) and outcome.has_short_body
    ]
    ready_candidates = tuple(
        issue
        for issue, _, outcome in issues_with_outcomes
        if isinstance(outcome, AFKReadyOutcome)
    )
    ready_readiness_by_number = {
        issue["number"]: readiness
        for issue, readiness, outcome in issues_with_outcomes
        if isinstance(outcome, AFKReadyOutcome)
    }
    return PlanningReadinessResult(
        ready_candidates=ready_candidates,
        ready_readiness_by_number=ready_readiness_by_number,
        malformed_body_issues=tuple(body_malformed),
        malformed_slice_mode_issues=tuple(slice_malformed),
        label_sync_actions=(
            _needs_info_actions(
                [(issue, outcome) for issue, _, outcome in issues_with_outcomes], cfg
            )
            + _needs_slice_type_actions(
                [(issue, outcome) for issue, _, outcome in issues_with_outcomes], cfg
            )
        ),
        blocker_summary_inputs=BlockerSummaryInputs(
            malformed_slice_mode_issues=tuple(slice_malformed),
            malformed_body_issues=tuple(body_malformed),
            malformed_slice_mode_readiness=tuple(slice_malformed_readiness),
            malformed_body_readiness=tuple(body_malformed_readiness),
        ),
    )
